import ProjectDescription

public extension Workspace {
    static func createWorkspace(
        name: String,
        projects: [Path]
    ) -> Self {
        return .init(name: name,
                     projects: projects,
                     generationOptions: .options(enableAutomaticXcodeSchemes: false,
                                                 autogeneratedWorkspaceSchemes: .disabled,
                                                 lastXcodeUpgradeCheck: nil,
                                                 renderMarkdownReadme: true))
    }
}
