import ProjectDescription
import ProjectDescriptionHelpers

func createShareExtension() -> Target {
    let shareExtensionActivationRule = """
SUBQUERY (
              extensionItems,
              $extensionItem,
              SUBQUERY (
              $extensionItem.attachments,
              $attachment,
                ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data" ||
                ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url" ||
                ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.apple.pkpass"
              ).@count >= 1
            ).@count == 1
"""

    let infoPlist: InfoPlist = .extendingDefault(with: [
        "NSExtension": [
            "NSExtensionPointIdentifier": "com.apple.share-services",
            "NSExtensionPrincipalClass": "$(PRODUCT_MODULE_NAME).ShareViewController",
            "NSExtensionAttributes": [
                "IntentsSupported": [
                    "INSendMessageIntent"
                ],
                "NSExtensionActivationRule": .string(shareExtensionActivationRule)
            ]
        ],
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        "NSHumanReadableCopyright": .init(stringLiteral: Constants.nsHumanReadableCopyrightValue),
        "CFBundleDisplayName": "$(OBV_BUNDLE_DISPLAY_NAME_FOR_SHARE_EXTENSION)",
        "OBV_APP_GROUP_IDENTIFIER": "$(OBV_APP_GROUP_IDENTIFIER)"
    ])

    let target = Target.appExtension(name: "ObvMessengerShareExtension",
                                     bundleIdentifier: "$(OBV_PRODUCT_BUNDLE_IDENTIFIER_FOR_SHARE_EXTENSION)",
                                     infoPlist: infoPlist,
                                     sources: [ // This will need to be organized and not have target files from other targets
                                        "ObvMessengerShareExtension/*.swift",
                                        "ObvMessengerShareExtension/Operations/*.swift",
                                        "ObvMessenger/Constants/ObvMessengerConstants.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/CreateOrUpdatePersistedGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/DeletePersistedGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/MarkPublishedDetailsOfGroupV2AsSeenOperation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/RemoveUpdateInProgressForGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/UpdateGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Operations/Deleting messages and discussions/WipeAllReadOnceAndLimitedVisibilityMessagesAfterLockOutOperation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Operations/Sending messages/SendUnprocessedPersistedMessageSentOperation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Protocols/OperationProvidingLoadedItemProvider.swift",
                                        "ObvMessenger/CoreData/DataMigrationManagerForObvMessenger.swift",
                                        "ObvMessenger/CoreData/ObvMessengerPersistentContainer.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/CircleAndTitlesView.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/CircledCameraButtonView.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/CircledSymbolView.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/IdentityCardContentView.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/OlvidButton.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/ProfilePictureView.swift",
                                        "ObvMessenger/Invitation Flow/SubViews/TextView.swift",
                                        "ObvMessenger/LocalAuthentication/LocalAuthenticationViewController.swift",
                                        "ObvMessenger/LocalAuthentication/LocalAuthenticationViewControllerDelegate.swift",
                                        "ObvMessenger/Localization/CommonString.swift",
                                        "ObvMessenger/Main/Settings/AllSettings/Privacy/VerifyPasscodeViewController.swift",
                                        "ObvMessenger/Managers/HardLinksToFylesManager/HardLinksToFylesManager.swift",
                                        "ObvMessenger/Managers/IntentManager/IntentManagerUtils.swift",
                                        "ObvMessenger/Managers/KeycloakManager/KeycloakServerRevocationsAndStuff.swift",
                                        "ObvMessenger/Managers/KeycloakManager/KeycloakUserDetailsAndStuff.swift",
                                        "ObvMessenger/Managers/LocalAuthenticationManager/LocalAuthenticationManager.swift",
                                        "ObvMessenger/Managers/SnackBarManager/OlvidSnackBarCategory.swift",
                                        "ObvMessenger/Managers/ThumbnailManager/ThumbnailManager.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/Note.swift",
                                        "ObvMessenger/Notifications/HardLinksToFylesNotifications.swift",
                                        "ObvMessenger/Notifications/ObvMessengerGroupV2Notifications.swift",
                                        "ObvMessenger/Notifications/ObvMessengerInternalNotification.swift",
                                        "ObvMessenger/Onboarding/BackupRestore/ObvImageButton.swift",
                                        "ObvMessenger/OwnedIdentityChooser/LatestCurrentOwnedIdentityStorage.swift",
                                        "ObvMessenger/OwnedIdentityChooser/OwnedIdentityChooserViewController.swift",
                                        "ObvMessenger/Singletons/AppTheme.swift",
                                        "ObvMessenger/Singletons/ObvStack.swift",
                                        "ObvMessenger/Singletons/ObvUserActivitySingleton/ObvUserActivityType.swift",
                                        "ObvMessenger/TableViewControllers/Contacts/MultiContactChooserViewController/FloatingActionButton.swift",
                                        "ObvMessenger/Types/OlvidURL.swift",
                                        "ObvMessenger/Types/OlvidUserId.swift",
                                        "ObvMessenger/UIElements/HUD/SwiftUI/ObvActivityIndicatorView.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/HUDs/ObvHUDView.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/HUDs/ObvIconHUD.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/HUDs/ObvLoadingHUD.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/HUDs/ObvTextHUD.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/ObvCanShowHUD.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/ObvHUDType.swift",
                                        "ObvMessenger/UIElements/HUD/UIKit/UIViewController+ObvCanShowHUD.swift",
                                        "ObvMessenger/UIElements/ImageEditor.swift",
                                        "ObvMessenger/UIElements/ImagePicker.swift",
                                        "ObvMessenger/UIElements/InitialCircleView.swift",
                                        "ObvMessenger/UIElements/ObvCardView.swift",
                                        "ObvMessenger/UIElements/PasscodeUtils.swift",
                                        "ObvMessenger/UIElements/StandardViewControllerSubclasses/ObvNavigationController.swift",
                                        "ObvMessenger/UIElements/SwiftUIUtils.swift",
                                        "ObvMessenger/UIElements/UIButtonViewController.swift",
                                        "ObvMessenger/Utils/Atomic.swift",
                                        "ObvMessenger/Utils/BlockBarButtonItem.swift",
                                        "ObvMessenger/Utils/Concurrency.swift",
                                        "ObvMessenger/Utils/Loading Item Providers/LoadItemProviderOperation.swift",
                                        "ObvMessenger/Utils/ObvDeepLink.swift",
                                        "ObvMessenger/Utils/SoundsPlayer.swift",
                                        "ObvMessenger/Utils/TimeUtils.swift",
                                        "ObvMessenger/Utils/UIView+AppTheme.swift",
                                        "ObvMessenger/Utils/UIView+EdgeConstraints.swift",
                                        "ObvMessenger/Utils/UIViewController+ContentController.swift",
                                        "ObvMessenger/Utils/URL+MoveToTrash.swift",
                                        "ObvMessenger/Utils/URL+Thumbnail.swift",
                                        "ObvMessenger/Utils/UIImage+Utils.swift",
                                        "ObvMessenger/VoIP/Helpers/CallSounds.swift",
                                        "ObvMessenger/Types/ObvLinkMetadata.swift",
                                        "ObvMessenger/Types/ObvLinkMetadata+LPLinkMetadata.swift",
                                        "ObvMessenger/ObvMessengerShareExtension/Operations/FetchAndCacheObvLinkMetadataForFirstURLInLoadedItemProvidersOperation.swift",
                                              ],
                                     resources: [
                                        "ObvMessenger/*.xcstrings",
                                        "ObvMessenger/Assets.xcassets",
                                        "ObvMessenger/LaunchScreen.storyboard",
                                        "ObvMessengerShareExtension/PrivacyInfo.xcprivacy",
                                     ],
                                     entitlements: "ObvMessengerShareExtension/ObvMessengerShareExtension.entitlements",
                                     dependencies: [
                                        .Modules.coreDataStack,
                                        .Modules.obvUI,
                                        .Engine.obvEngine,
                                        .sdk(name: "UIKit", type: .framework),
                                        .Modules.Platform.base,
                                        .Modules.obvUICoreData
                                     ],
                                     settings: .defaultAppExtensionTargetSettings(),
                                     coreDataModels: [
                                        .init("ObvMessenger/CoreData/ObvMessenger.xcdatamodeld")
                                     ])

    return target
}

func createNotificationServiceExtension() -> Target {
    let infoPlist: InfoPlist = .extendingDefault(with: [
        "NSExtension": [
            "NSExtensionPointIdentifier": "com.apple.usernotifications.service",
            "NSExtensionPrincipalClass": "$(PRODUCT_MODULE_NAME).NotificationService",
        ],
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        "NSHumanReadableCopyright": .init(stringLiteral: Constants.nsHumanReadableCopyrightValue),
        "CFBundleDisplayName": "$(OBV_BUNDLE_DISPLAY_NAME_FOR_NOTIFICATION_SERVICE_EXTENSION)",
        "OBV_APP_GROUP_IDENTIFIER": "$(OBV_APP_GROUP_IDENTIFIER)"
    ])

    let target = Target.appExtension(name: "ObvMessengerNotificationServiceExtension",
                                     bundleIdentifier: "$(OBV_PRODUCT_BUNDLE_IDENTIFIER_FOR_NOTIFICATION_SERVICE_EXTENSION)",
                                     infoPlist: infoPlist,
                                     sources: [
                                        "ObvMessenger/Constants/ObvMessengerConstants.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/CreateOrUpdatePersistedGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/DeletePersistedGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/MarkPublishedDetailsOfGroupV2AsSeenOperation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/RemoveUpdateInProgressForGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/ContactGroupCoordinator/Operations/UpdateGroupV2Operation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Operations/CallLog/CleanCallLogContactsOperation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Operations/CallLog/ReportEndCallOperation.swift",
                                        "ObvMessenger/Coordinators/PersistedDiscussionsUpdatesCoordinator/Operations/Receiving messages/ExtractReceivedExtendedPayloadOperation.swift",
                                        "ObvMessenger/CoreData/DataMigrationManagerForObvMessenger.swift",
                                        "ObvMessenger/CoreData/ObvMessengerPersistentContainer.swift",
                                        "ObvMessenger/LocalAuthentication/LocalAuthenticationViewControllerDelegate.swift",
                                        "ObvMessenger/Localization/CommonString.swift",
                                        "ObvMessenger/Localization/UserNotificationCreator+Strings.swift",
                                        "ObvMessenger/Managers/HardLinksToFylesManager/HardLinksToFylesManager.swift",
                                        "ObvMessenger/Managers/IntentManager/IntentManager.swift",
                                        "ObvMessenger/Managers/IntentManager/IntentManagerUtils.swift",
                                        "ObvMessenger/Managers/SnackBarManager/OlvidSnackBarCategory.swift",
                                        "ObvMessenger/Managers/ThumbnailManager/ThumbnailManager.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/Note.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/ObvUserNotificationIdentifier.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UNNotificationRequestWithDate.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UserDefaultsKeyForBadge.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UserNotificationAction.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UserNotificationCategory.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UserNotificationCreator.swift",
                                        "ObvMessenger/Managers/UserNotificationManager/UserNotificationsScheduler.swift",
                                        "ObvMessenger/Notifications/HardLinksToFylesNotifications.swift",
                                        "ObvMessenger/Notifications/MessengerInternalNotification.swift",
                                        "ObvMessenger/Notifications/ObvMessengerGroupV2Notifications.swift",
                                        "ObvMessenger/Notifications/ObvMessengerInternalNotification.swift",
                                        "ObvMessenger/Singletons/AppTheme.swift",
                                        "ObvMessenger/Singletons/ObvStack.swift",
                                        "ObvMessenger/Singletons/ObvUserActivitySingleton/ObvUserActivityType.swift",
                                        "ObvMessenger/Types/OlvidURL.swift",
                                        "ObvMessenger/Types/OlvidUserId.swift",
                                        "ObvMessenger/Utils/Bindings.swift",
                                        "ObvMessenger/Utils/Concurrency.swift",
                                        "ObvMessenger/Utils/NSNumber+Utils.swift",
                                        "ObvMessenger/Utils/ObvCompressor.swift",
                                        "ObvMessenger/Utils/ObvDeepLink.swift",
                                        "ObvMessenger/Utils/ProgressUtils.swift",
                                        "ObvMessenger/Utils/SoundsPlayer.swift",
                                        "ObvMessenger/Utils/ThumbnailWorker.swift",
                                        "ObvMessenger/Utils/TimeUtils.swift",
                                        "ObvMessenger/Utils/UIDevice+AlertControllerStyle.swift",
                                        "ObvMessenger/Utils/UIImage+Utils.swift",
                                        "ObvMessenger/Utils/UIView+AppTheme.swift",
                                        "ObvMessenger/VoIP/Call/GenericCall.swift",
                                        "ObvMessenger/VoIP/CallParticipant/CallParticipant.swift",
                                        "ObvMessenger/VoIP/CallParticipant/CallParticipantUpdateKind.swift",
                                        "ObvMessenger/VoIP/Helpers/CallSounds.swift",
                                        "ObvMessenger/VoIP/VoIPNotification/CallUpdateKind.swift",
                                        "ObvMessengerNotificationServiceExtension/NotificationService.swift",
                                     ],
                                     resources: [
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Modular.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Tweet.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-springy.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-Train-1.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Turkey-gobble.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-paranoid.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM12.caf",
                                        "ObvMessenger/*.xcstrings",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Woodblock.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Cuckoo.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-bus.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Chicken-Roster.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Puppy.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Cicada.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-oringz452.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-are-you-kidding.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Crow.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Koto.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Cow-moo.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Chicken.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-boat.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Goat.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-car.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel07.caf",
                                        "ObvMessenger/Assets.xcassets",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Turkey-noises.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Duck-Quack.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-taxi.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Block.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Duck-Quacks.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-frenzy.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Unstrung.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Coqui.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-busy.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Owl-tawny.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-cinema-bring-the-drama.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Sheep.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Bell.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-oh-really.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-feline-Panthera.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-hey-champ.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Calm.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-enough-with-the-talking.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-nestling.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Eagle.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-strike.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Unphased.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Quantizer/Synth-Quantizer11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-dixie.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Horse-whinnies.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Koto/Koto04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Saxo/Saxo03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Owl-horned.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Magpie.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel03.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-FM/Synth-FM02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Glockenspiel/Glockenspiel08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Sonar.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Harp/Harp01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Guitar/Clav-Guitar06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Cloud.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Pecussive/Synth-Pecussive10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-in-forest.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/neutral-Polite.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Flute/Flute12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-feline-Tiger.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings11.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Cardinal.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano01.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-horn-Train-2.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Piano/Piano07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-Funny-fanfare.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Chordal/Synth-Chordal04.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Droplets/Synth-Droplets12.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Pipa/Pipa02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-Weird.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Brass/Brass02.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Airship/Synth-Airship07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Bassoon/Bassoon05.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Frog.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-bird-Warning.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp13.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-nice-cut.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/toy-Circus-clown-horn.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/alarm-chime.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-LushArp/Synth-LushArp06.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Strings/Strings09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Cosmic/Synth-Cosmic09.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Chicken-Rooster.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/animal-Elephant.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clav-Fly/Clav-Fly08.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Clarinet/Clarinet10.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Synth-Emotive/Synth-Emotive07.caf",
                                        "ObvMessenger/Managers/UserNotificationManager/Sounds/Oboe/Oboe09.caf",
                                        "ObvMessengerNotificationServiceExtension/PrivacyInfo.xcprivacy",
                                     ],
                                     entitlements: "ObvMessengerNotificationServiceExtension/ObvMessengerNotificationServiceExtension.entitlements",
                                     dependencies: [
                                        .Modules.coreDataStack,
                                        .Modules.obvUI,
                                        .Engine.obvEngine,
                                        .sdk(name: "UserNotifications", type: .framework),
                                        .sdk(name: "UIKit", type: .framework),
                                        .Modules.Platform.base,
                                        .Modules.obvUICoreData
                                     ],
                                     settings: .defaultAppExtensionTargetSettings(),
                                     coreDataModels: [
                                        .init("ObvMessenger/CoreData/ObvMessenger.xcdatamodeld")
                                     ])

    return target
}

func createIntentsServiceExtension() -> Target {
    let infoPlist: InfoPlist = .extendingDefault(with: [
        "NSExtension": [
            "NSExtensionAttributes" : [
                "IntentsRestrictedWhileLocked" : [],
                "IntentsSupported" : ["INStartCallIntent"]
            ],
            "NSExtensionPointIdentifier" : "com.apple.intents-service",
            "NSExtensionPrincipalClass" : "$(PRODUCT_MODULE_NAME).IntentHandler"
        ],
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "NSHumanReadableCopyright": .init(stringLiteral: Constants.nsHumanReadableCopyrightValue),
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        "CFBundleDisplayName": "$(OBV_BUNDLE_DISPLAY_NAME_FOR_INTENTS_EXTENSION)",
    ])

    let target = Target.appExtension(name: "ObvMessengerIntentsExtension",
                                     bundleIdentifier: "$(OBV_PRODUCT_BUNDLE_IDENTIFIER_FOR_INTENTS_EXTENSION)",
                                     deploymentTargets: .init(iOS: "15.5"),
                                     infoPlist: infoPlist,
                                     sources: [
                                        "ObvMessengerIntentsExtension/IntentHandler.swift"
                                     ],
                                     resources: [],
                                     entitlements: "ObvMessengerIntentsExtension/ObvMessengerIntentsExtension.entitlements",
                                     dependencies: [
                                        .sdk(name: "Intents", type: .framework, status: .required)
                                     ],
                                     settings: .defaultAppExtensionTargetSettings(),
                                     coreDataModels: [])

    return target
}


func createApp(shareExtension: Target,
               notificationExtension: Target,
               intentsExtension: Target,
               devMode: Bool) -> Target {
    let infoPlist: InfoPlist = .extendingDefault(with: [
        "BGTaskSchedulerPermittedIdentifiers": [
            "io.olvid.background.tasks"
        ],
        "CFBundleDocumentTypes": [
            [
                "CFBundleTypeName" : "com.adobe.pdf",
                "CFBundleTypeRole" : "None",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["com.adobe.pdf"]
            ],
            [
                "CFBundleTypeIconFiles" : [],
                "CFBundleTypeName" : "Olvid Backup",
                "LSHandlerRank" : "Owner",
                "LSItemContentTypes" : ["io.olvid.type.olvidbackup"]
            ],
            [
                "CFBundleTypeIconFiles" : [],
                "CFBundleTypeName" : "Olvid Link Preview",
                "LSHandlerRank" : "Owner",
                "LSItemContentTypes" : ["olvid.link-preview"]
            ],
            [
                "CFBundleTypeName" : "public.comma-separated-values-text",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["public.comma-separated-values-text"]
            ],
            [
                "CFBundleTypeName" : "Microsoft Word 97 document",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["com.microsoft.word.doc"]
            ],
            [
                "CFBundleTypeName" : "Microsoft Word document",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["org.openxmlformats.wordprocessingml.document"]
            ],
            [
                "CFBundleTypeName" : "Microsoft Powerpoint document",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["org.openxmlformats.presentationml.presentation"]
            ],
            [
                "CFBundleTypeName" : "Microsoft Excel document",
                "LSHandlerRank" : "Default",
                "LSItemContentTypes" : ["org.openxmlformats.spreadsheetml.sheet"]
            ],
        ],
        "CFBundleURLTypes": [
            [
                "CFBundleTypeRole" : "Editor",
                "CFBundleURLSchemes" : [
                    devMode ? "olvid.dev" : "olvid"
                ]
            ]
        ],
        "CFBundleDisplayName": "$(OBV_BUNDLE_DISPLAY_NAME)",
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "NSHumanReadableCopyright": .init(stringLiteral: Constants.nsHumanReadableCopyrightValue),
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        "ITSAppUsesNonExemptEncryption": false,
        "LSApplicationCategoryType": "public.app-category.social-networking",
        "LSRequiresIPhoneOS": true,
        "LSSupportsOpeningDocumentsInPlace": true,
        "NSCameraUsageDescription": "Access to the camera allows you to scan the QR code of your contacts and to take pictures and videos right from within a discussion.",
        "NSFaceIDUsageDescription": "Use Face ID to access Olvid",
        "NSMicrophoneUsageDescription": "Allowing access to the microphone is required to make secure audio calls and to record movies and voice messages.",
        "NSPhotoLibraryAddUsageDescription": "Write access is required to save a picture to your photo library. Please note that Olvid will not have access to the other photos of your photo library.",
        "NSUserActivityTypes" : [
            "INSendMessageIntent",
            "io.olvid.messenger.continueDiscussion",
            "io.olvid.messenger.other",
            "io.olvid.messenger.watchLatestDiscussions",
            "io.olvid.messenger.displaySingleContact",
            "io.olvid.messenger.displayContacts",
            "io.olvid.messenger.displayGroups",
            "io.olvid.messenger.displayInvitations",
            "io.olvid.messenger.displaySettings",
            "io.olvid.messenger.displaySingleGroup",
            "io.olvid.messenger.unknown"
        ],
        "OBV_APP_GROUP_IDENTIFIER" : "$(OBV_APP_GROUP_IDENTIFIER)",
        "OBV_DEVELOPMENT_MODE" : "$(OBV_DEVELOPMENT_MODE)",
        "OBV_HOST_FOR_CONFIGURATIONS" : "$(OBV_HOST_FOR_CONFIGURATIONS)",
        "OBV_HOST_FOR_INVITATIONS" : "$(OBV_HOST_FOR_INVITATIONS)",
        "OBV_HOST_FOR_OPENID_REDIRECT" : "$(OBV_HOST_FOR_OPENID_REDIRECT)",
        "OBV_SERVER_URL" : "$(OBV_SERVER_URL)",
        "UIApplicationSceneManifest" : [
            "UIApplicationSupportsMultipleScenes" : false,
            "UISceneConfigurations" : [
                "UIWindowSceneSessionRoleApplication" : [
                    [
                        "UISceneConfigurationName" : "Default configuration",
                        "UISceneDelegateClassName" : "$(PRODUCT_MODULE_NAME).SceneDelegate"
                    ]
                ]
            ]
        ],
        "UIBackgroundModes" : [
            "audio",
            "fetch",
            "remote-notification",
            "voip"
        ],
        "UIFileSharingEnabled": true,
        "UILaunchStoryboardName": "LaunchScreen",
        "UIStatusBarStyle": "UIStatusBarStyleLightContent",
        "UISupportedInterfaceOrientations" : [
            "UIInterfaceOrientationPortrait",
            "UIInterfaceOrientationLandscapeLeft",
            "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad" : [
            "UIInterfaceOrientationPortrait",
            "UIInterfaceOrientationPortraitUpsideDown",
            "UIInterfaceOrientationLandscapeLeft",
            "UIInterfaceOrientationLandscapeRight"
        ],
        "UTExportedTypeDeclarations" : [
            [
                "UTTypeConformsTo" : [
                    "public.data",
                    "public.content",
                ],
                "UTTypeDescription" : "Olvid Backup",
                "UTTypeIconFiles" : [],
                "UTTypeIdentifier" : "io.olvid.type.olvidbackup",
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "olvidbackup"
                    ]
                ]
            ],
            [
                "UTTypeConformsTo" : [
                    "public.data",
                    "public.content",
                ],
                "UTTypeDescription" : "Olvid Link Preview",
                "UTTypeIconFiles" : [],
                "UTTypeIdentifier" : "olvid.link-preview",
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "olvidlinkpreview"
                    ],
                    "public.mime-type" : [
                        "olvid/link-preview"
                    ],
                ]
            ]
        ],
        "NSAppTransportSecurity" : [
            "NSAllowsArbitraryLoads" : true
        ],
        "UTImportedTypeDeclarations" : [
            [
                "UTTypeDescription" : "Web Internet Location",
                "UTTypeIdentifier" : "com.apple.web-internet-location",
                "UTTypeConformsTo" : [
                    "public.data",
                ],
            ],
            [
                "UTTypeDescription" : "Microsoft Word 97 document",
                "UTTypeIdentifier" : "com.microsoft.word.doc",
                "UTTypeConformsTo" : [
                    "public.data",
                ],
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "doc",
                    ],
                ],
            ],
            [
                "UTTypeDescription" : "Microsoft Word document",
                "UTTypeIdentifier" : "org.openxmlformats.wordprocessingml.document",
                "UTTypeConformsTo" : [
                    "public.data",
                ],
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "docx",
                    ],
                ],
            ],
            [
                "UTTypeDescription" : "Microsoft Powerpoint document",
                "UTTypeIdentifier" : "org.openxmlformats.presentationml.presentation",
                "UTTypeConformsTo" : [
                    "public.data",
                ],
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "pptx",
                    ],
                ],
            ],
            [
                "UTTypeDescription" : "Microsoft Excel document",
                "UTTypeIdentifier" : "org.openxmlformats.spreadsheetml.sheet",
                "UTTypeConformsTo" : [
                    "public.data",
                ],
                "UTTypeTagSpecification" : [
                    "public.filename-extension" : [
                        "xlsx",
                    ],
                ],
            ],
        ],
    ])

    let dependencies: [TargetDependency] = [
        .target(shareExtension),
        .target(notificationExtension),
        .target(intentsExtension),
        .Engine.obvFlowManager,
        .Engine.obvTypes,
        .Engine.obvServerInterface,
        .Modules.obvUI,
        .Engine.obvNetworkFetchManager,
        .Engine.bigInt,
        .Engine.jws,
        .Engine.obvIdentityManager,
        .init(.webRTC),
        .package(product: "AppAuth"),
        .Engine.obvOperation,
        .Engine.obvNotificationCenter,
        .Engine.obvNetworkSendManager,
        .Engine.obvEncoder,
        //.init(.orderedCollections),
        .Engine.obvDatabaseManager,
        .Engine.obvChannelManager,
        .Engine.obvBackupManager,
        .Engine.obvSyncSnapshotManager,
        .Engine.obvCrypto,
        .Engine.obvEngine,
        .Engine.obvProtocolManager,
        .Modules.obvUICoreData,
        //.Engine.obvMetaManager,
        .Modules.olvidUtils,
        .Modules.obvDesignSystem,
        .Modules.obvSettings,
        .Modules.Platform.base,
        .Modules.Discussions.Mentions.AutoGrowingTextView.textViewDelegateProxy,
        .Modules.Platform.uiKitAdditions,
        .Modules.Components.textInputShortcutsResultView,
        .Modules.Discussions.Mentions.Builders.composeMessage,
        .Modules.Discussions.Mentions.Builders.buildersShared,
        .Modules.Discussions.scrollToBottomButton,
    ]

    let mainApp = Target.mainApp(name: devMode ? "Olvid_dev" : "Olvid",
                                 infoPlist: infoPlist,
                                 sources: [
                                    "ObvMessenger/**/*.swift",
                                    "ObvMessenger/**/*.xcmappingmodel",
                                 ],
                                 resources: [
                                    "ObvMessenger/**/*.caf",
                                    "ObvMessenger/**/*.mp3",
                                    "ObvMessenger/**/*.xib",
                                    "ObvMessenger/**/*.storyboard",
                                    "ObvMessenger/**/*.xcstrings",
                                    "ObvMessenger/**/*.lproj/AppIntentVocabulary.plist",
                                    "ObvMessenger/Assets.xcassets",
                                    "ObvMessenger/Settings.bundle",
                                    "ObvMessenger/PrivacyInfo.xcprivacy",
                                 ],
                                 entitlements: "ObvMessenger/ObvMessenger.entitlements",
                                 dependencies: dependencies,
                                 settings: .defaultMainAppTargetSettings(),
                                 coreDataModels: [
                                    .init("ObvMessenger/CoreData/ObvMessenger.xcdatamodeld")
                                 ],
                                 additionalFiles: [
                                    "ObvMessenger/**/*.md",
                                    "ObvMessenger/**/*.txt",
                                 ])

    return mainApp
}


let shareExtension = createShareExtension()

let notificationExtension = createNotificationServiceExtension()

let intentsExtension = createIntentsServiceExtension()

let app = createApp(shareExtension: shareExtension,
                    notificationExtension: notificationExtension,
                    intentsExtension: intentsExtension,
                    devMode: false)

let appDev = createApp(shareExtension: shareExtension,
                       notificationExtension: notificationExtension,
                       intentsExtension: intentsExtension,
                       devMode: true)

let project = Project.createProject(name: "ObvMessenger",
                                    packages: [],
                                    targets: [
                                        app,
                                        appDev,
                                        shareExtension,
                                        notificationExtension,
                                        intentsExtension
                                    ])
