import ProjectDescription

extension Workspace {
    
    public static func createWorkspace(name: String, projects: [Path]) -> Self {
        return .init(name: name,
                     projects: projects,
                     schemes: [],
                     fileHeaderTemplate: .string(Constant.fileHeaderTemplate),
                     additionalFiles: [],
                     generationOptions: .options(enableAutomaticXcodeSchemes: false,
                                                 autogeneratedWorkspaceSchemes: .disabled,
                                                 lastXcodeUpgradeCheck: nil,
                                                 renderMarkdownReadme: true))
        
    }
    
}
